# Generated by Django 4.2.6 on 2025-01-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_neuralnetworkdescription_af_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
