# Generated by Django 4.2.17 on 2025-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pageview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('page_path', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
